---
# tasks file for pve_ct_download
#
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝
#     ██║   ██╔══██║╚════██║██╔═██╗
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# Filters and selects nodes for template application.
# -----------------------------------------------------------------------------
- name: >-
    | facts.yml | Extract node names from Proxmox node information
  ansible.builtin.set_fact:
    all_nodes: >-
      {{ parsed_all_nodes.proxmox_nodes | map(attribute='node') }}
  tags:
    - prerequisite
    - storage_container

# -----------------------------------------------------------------------------
# Filters storages that support template storage and ensures at least one is available.
# -----------------------------------------------------------------------------
- name: >-
    | facts.yml | Filter storages supporting VZ templates
  ansible.builtin.set_fact:
    template_storages: >-
        {{ this.proxmox_storages | selectattr('content', 'search', 'vztmpl') | map(attribute='storage') | list }}
  tags:
    - prerequisite
    - storage_template

- name: >-
    | facts.yml | Fail if no suitable storage is found
  ansible.builtin.fail:
    msg: "No suitable storage(s) supporting VZ templates found in the cluster."
  when: template_storages|length == 0
  tags:
    - prerequisite
    - storage_template
