---
# tasks file for pve_ct_download
#
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝
#     ██║   ██╔══██║╚════██║██╔═██╗
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# Fetches the list of templates from the specified URL.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | preliminary | Get the list of files from the URL
  ansible.builtin.uri:
    url: "{{ pve_base_url }}"
    return_content: true
  register: this
  failed_when:
    - "this.status != 200"

# -----------------------------------------------------------------------------
# Extracts the latest image for the specified OS based on naming conventions.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | preliminary | Extract and parse images and date from content
  ansible.builtin.set_fact:
    pcl_latest_image: "{{ this.content | lastest_image(pve_template) }}"

# -----------------------------------------------------------------------------
# Ensures that a valid image is found for the OS, or the task fails.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | preliminary | Fail if no image is found for the specified OS
  ansible.builtin.fail:
    msg: "No image found for OS {{ pve_template }}."
  when:
    - pcl_latest_image is not defined
    - pcl_latest_image|length == 0
