---
# tasks file for pve_ct_download
#
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝
#     ██║   ██╔══██║╚════██║██╔═██╗
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# Retrieves a list of nodes in the Proxmox cluster.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | use_password | Retrieve Proxmox node information
  community.general.proxmox_node_info:
    api_host: "{{ pve_host }}"                                  # Proxmox API host
    api_password: "{{ pve_password }}"                          # Proxmox password to authenticate with
    api_port: "{{ pve_port | default(8006) }}"                  # Proxmox API port
    api_user: "{{ pve_tokenid.split('!')[0] }}"                 # Proxmox API user extracted from token
    validate_certs: "{{ pve_validate_certs | default(false) }}" # SSL certificate validation
  register: pcl_parsed_nodes
  tags:
    - prerequisite
    - storage_container

# -----------------------------------------------------------------------------
# Retrieve Proxmox storage information.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | use_password | Retrieve Proxmox storage information
  community.general.proxmox_storage_info:
    api_host: "{{ pve_host }}"                                  # Proxmox API host
    api_password: "{{ pve_password }}"                          # Proxmox password to authenticate with
    api_port: "{{ pve_port | default(8006) }}"                  # Proxmox API port
    api_user: "{{ pve_tokenid.split('!')[0] }}"                 # Proxmox API user extracted from token
    validate_certs: "{{ pve_validate_certs | default(false) }}" # SSL certificate validation
  register: this
  tags:
    - prerequisite

# -----------------------------------------------------------------------------
# Import task the current playbook for subsequent execution
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | use_password | Import 'set_facts' task statically
  ansible.builtin.include_tasks: "facts.yml"
  tags:
    - prerequisite
    - storage_container

# -----------------------------------------------------------------------------
# Downloads the latest template image to the specified storage on the
# selected nodes.
# -----------------------------------------------------------------------------
- name: (pve_ct_download) | use_password | Download Proxmox appliance container template(s)
  community.general.proxmox_template:
    api_host: "{{ pve_host }}"                                  # Proxmox API host
    api_password: "{{ pve_password }}"                          # Proxmox password to authenticate with
    api_port: "{{ pve_port | default(8006) }}"                  # Proxmox API port
    api_user: "{{ pve_tokenid.split('!')[0] }}"                 # Proxmox API user extracted from token
    validate_certs: "{{ pve_validate_certs | default(false) }}" # SSL certificate validation
    node: "{{ item.0 }}"
    state: "present"
    storage: "{{ item.1 }}"
    template: "{{ item.2 }}"
    timeout: "{{ pve_timeout | default(0) }}"
    force: "{{ pve_force | default(false) }}"
  loop: "{{ query('nested', pcl_nodes, pcl_filtered_storages, pcl_latest_image) }}"
